CREATE DATABASE BANHANGKT
GO
USE BANHANGKT
GO

CREATE TABLE ACOUNT
(
	STT INT IDENTITY NOT NULL UNIQUE, 
	id VARCHAR(10) PRIMARY KEY,
	name NVARCHAR(100) NOT NULL,
	dateOfBirt DATE NOT NULL,
	sex INT NOT NULL,                                --1 la nam; 0 la nu.
	-- typeWord gom admin; thu kho; thu quy; nhan vien ban hang.
	telephone VARCHAR(10) NOT NULL,
	email VARCHAR(100) NOT NULL,
	typeWord VARCHAR(20) NOT NULL,
	userName VARCHAR(100) NOT NULL,
	passwords VARCHAR(100) NOT NULL,
	pay FLOAT,
)
GO

CREATE TABLE ITEM
(
	STT INT IDENTITY NOT NULL UNIQUE, 
	id VARCHAR(10) PRIMARY KEY,
	name NVARCHAR(100) NOT NULL,
	price FLOAT NOT NULL,
	countItem INT NOT NULL,
	note NVARCHAR(1000),
	idAcount VARCHAR(10) NOT NULL,
	idCatalogy VARCHAR(10) NOT NULL,

	FOREIGN KEY (idAcount) REFERENCES dbo.ACOUNT(id),
	FOREIGN KEY (idCatalogy) REFERENCES dbo.ITEMCATALOGY(id),
)
GO

CREATE TABLE ITEMCATALOGY
(
	STT INT IDENTITY NOT NULL UNIQUE, 
	id VARCHAR(10) PRIMARY KEY,
	name NVARCHAR(100) NOT NULL,
)
GO

CREATE TABLE BILL
(
	STT INT IDENTITY NOT NULL UNIQUE, 
	id VARCHAR(10) PRIMARY KEY,
	idAcount VARCHAR(10) NOT NULL,
	dateCheckIn DATE NOT NULL,
	moneyBill FLOAT NOT NULL,

	FOREIGN KEY (idAcount) REFERENCES dbo.ACOUNT(id),
)
GO

CREATE TABLE BILLINFOR
(
	STT INT IDENTITY NOT NULL UNIQUE, 
	id VARCHAR(10) PRIMARY KEY,
	idItem VARCHAR(10) NOT NULL,
	idBill VARCHAR(10) NOT NULL,
	countItems INT NOT NULL,

	FOREIGN KEY (idBill) REFERENCES dbo.BILL(id),
	FOREIGN KEY (idItem) REFERENCES dbo.ITEM(id),

)
GO

CREATE TABLE MONEYS
(
	STT INT IDENTITY NOT NULL UNIQUE, 
	total FLOAT,
	id VARCHAR(10) PRIMARY KEY,
	note NVARCHAR(1000) NOT NULL,
	dates DATE NOT NULL,
)
GO

CREATE TABLE HOUSE
(
	STT INT IDENTITY NOT NULL UNIQUE, 
	id VARCHAR(10) PRIMARY KEY NOT NULL,
	idItem VARCHAR(10) NOT NULL,
	name NVARCHAR(100) NOT NULL,
	price FLOAT NOT NULL,
	countItem INT NOT NULL,
	note NVARCHAR(1000),
	idCatalogy VARCHAR(10) NOT NULL,
	dateAddItem DATE NOT NULL,

	FOREIGN KEY (idCatalogy) REFERENCES dbo.ITEMCATALOGY(id),
	FOREIGN KEY (idItem) REFERENCES dbo.ITEM(id),
)
GO
CREATE TABLE HISTORYLOGIN
(
	STT INT IDENTITY NOT NULL UNIQUE, 
	id VARCHAR(10) PRIMARY KEY,
	idAcount VARCHAR(10) NOT NULL,
	dateLoin DATE NOT NULL,

	FOREIGN KEY (idAcount) REFERENCES dbo.ACOUNT(id)
)
GO

CREATE PROC FlogIn

	@username VARCHAR(100),
	@password VARCHAR(100)

AS
BEGIN
	SELECT * FROM dbo.ACOUNT WHERE userName = @username AND passwords = @password
END
GO


--nháp--
update dbo.ACOUNT set typeWord = 'Admin' where id = '1234'
select * from dbo.HISTORYLOGIN